apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
  namespace: alfa
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alfa
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

